--
-- PostgreSQL database dump
--

\restrict 75OxdbnU1nQZNHMEESMytMt3uTgaAOfknstl9teBtAZUxj0nZrF4gyE8NXxTBEt

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.0

-- Started on 2026-03-05 19:37:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 255 (class 1255 OID 249793)
-- Name: get_best_ideas_by_ranking(integer, text, text); Type: FUNCTION; Schema: public; Owner: admin
--

CREATE FUNCTION public.get_best_ideas_by_ranking(p_ranking_level integer, p_style_type text, p_cap_type text) RETURNS TABLE(symbol text, ranking integer, appearances bigint, max_delta double precision, source_etf_id integer, all_provider_ids integer[])
    LANGUAGE sql
    AS $$

	SELECT
	    be.symbol::TEXT,
	    be.ranking,
	    COUNT(DISTINCT be.provider_etf_id) AS appearances,
	    MAX(be.delta) AS max_delta,
	    (array_agg(be.provider_etf_id ORDER BY be.delta DESC))[1] AS source_etf_id,
	    array_agg(DISTINCT be.provider_etf_id) AS all_provider_ids
	
	FROM public.best_idea be
	JOIN public.ticker t ON be.symbol = t.symbol
	JOIN public.ticker_value tv ON tv.symbol = be.symbol
	JOIN (
	    SELECT symbol, MAX(value_date) AS max_date
	    FROM public.ticker_value
	    WHERE value_date >= CURRENT_DATE - INTERVAL '7 days'
	    GROUP BY symbol
	) latest_tv
	    ON tv.symbol = latest_tv.symbol
	   AND tv.value_date = latest_tv.max_date
	
	-- keep only the best ranking per symbol
	JOIN (
	    SELECT symbol, MIN(ranking) AS best_ranking
	    FROM public.best_idea
	    WHERE ranking <= p_ranking_level
	    GROUP BY symbol
	) best
	    ON be.symbol = best.symbol
	   AND be.ranking = best.best_ranking
	
	WHERE 
      -- Style Filter: Match style OR ignore if 'blend'
      (p_style_type = 'blend' OR t.style_type = p_style_type)
      
      AND 
      
      -- Cap Filter: Ignore if 'all_cap' OR match the market_cap logic
      (p_cap_type = 'all_cap' OR (
          CASE
              WHEN tv.market_cap >= 10000000000 THEN 'large'
              ELSE 'mid_small'
          END
      ) = p_cap_type)
	
	GROUP BY be.symbol, be.ranking
	ORDER BY be.ranking, appearances DESC, max_delta DESC;

$$;


ALTER FUNCTION public.get_best_ideas_by_ranking(p_ranking_level integer, p_style_type text, p_cap_type text) OWNER TO admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 235 (class 1259 OID 249859)
-- Name: account; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.account (
    id integer NOT NULL,
    name text NOT NULL,
    base_currency character varying(3) DEFAULT 'USD'::character varying,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text)
);


ALTER TABLE public.account OWNER TO admin;

--
-- TOC entry 237 (class 1259 OID 249869)
-- Name: account_cash_ledger; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.account_cash_ledger (
    id integer NOT NULL,
    account_id integer NOT NULL,
    transaction_date date NOT NULL,
    amount numeric(18,4) NOT NULL,
    entry_type text NOT NULL,
    description text
);


ALTER TABLE public.account_cash_ledger OWNER TO admin;

--
-- TOC entry 236 (class 1259 OID 249868)
-- Name: account_cash_ledger_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.account_cash_ledger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_cash_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 249961)
-- Name: account_holding_daily; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.account_holding_daily (
    account_id integer NOT NULL,
    holding_date date NOT NULL,
    symbol text NOT NULL,
    quantity numeric(18,8) NOT NULL,
    cost_basis numeric(18,4) NOT NULL,
    market_value numeric(18,4) NOT NULL,
    weight_percentage numeric(5,4) NOT NULL
);


ALTER TABLE public.account_holding_daily OWNER TO admin;

--
-- TOC entry 234 (class 1259 OID 249858)
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 249887)
-- Name: account_trade; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.account_trade (
    id integer NOT NULL,
    account_id integer NOT NULL,
    symbol text NOT NULL,
    trade_date date NOT NULL,
    side character varying(4) NOT NULL,
    quantity numeric(18,8) NOT NULL,
    price numeric(18,4) NOT NULL,
    commission numeric(18,4) DEFAULT 0,
    total_amount numeric(18,4) NOT NULL
);


ALTER TABLE public.account_trade OWNER TO admin;

--
-- TOC entry 238 (class 1259 OID 249886)
-- Name: account_trade_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.account_trade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_trade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 249775)
-- Name: best_idea; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.best_idea (
    provider_etf_id integer NOT NULL,
    symbol character varying(32) NOT NULL,
    value_date date NOT NULL,
    etf_weight double precision,
    benchmark_weight double precision,
    delta double precision,
    ranking integer
);


ALTER TABLE public.best_idea OWNER TO admin;

--
-- TOC entry 233 (class 1259 OID 249804)
-- Name: categorize_etf; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.categorize_etf (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    name text,
    cap_type text,
    style_type text,
    url text NOT NULL,
    wait_pre_events text,
    wait_post_events text,
    events jsonb,
    trigger_download jsonb,
    mapping jsonb,
    file_format character varying(10),
    last_downloaded timestamp without time zone
);


ALTER TABLE public.categorize_etf OWNER TO admin;

--
-- TOC entry 232 (class 1259 OID 249803)
-- Name: categorize_etf_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.categorize_etf ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorize_etf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 249733)
-- Name: fund; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.fund (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    style_type character varying(16) NOT NULL,
    cap_type character varying(16) NOT NULL,
    name text NOT NULL,
    last_updated timestamp without time zone
);


ALTER TABLE public.fund OWNER TO admin;

--
-- TOC entry 227 (class 1259 OID 249741)
-- Name: fund_holding; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.fund_holding (
    fund_id integer NOT NULL,
    symbol text NOT NULL,
    holding_date date NOT NULL,
    ranking integer NOT NULL
);


ALTER TABLE public.fund_holding OWNER TO admin;

--
-- TOC entry 228 (class 1259 OID 249758)
-- Name: fund_holding_change; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.fund_holding_change (
    fund_id integer NOT NULL,
    symbol text NOT NULL,
    change_date date NOT NULL,
    direction character varying(5) NOT NULL,
    ranking integer,
    appearances integer,
    max_delta double precision,
    top_delta_provider_etf_id integer,
    all_provider_etf_ids integer[]
);


ALTER TABLE public.fund_holding_change OWNER TO admin;

--
-- TOC entry 225 (class 1259 OID 249732)
-- Name: fund_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.fund ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 249918)
-- Name: interest_rate_config; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.interest_rate_config (
    id integer NOT NULL,
    effective_date date NOT NULL,
    annual_rate numeric(5,4) NOT NULL
);


ALTER TABLE public.interest_rate_config OWNER TO admin;

--
-- TOC entry 240 (class 1259 OID 249917)
-- Name: interest_rate_config_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.interest_rate_config ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.interest_rate_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 249795)
-- Name: log; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.log (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    process character varying(20),
    log_type character varying(20),
    code character varying(20),
    msg text
);


ALTER TABLE public.log OWNER TO admin;

--
-- TOC entry 230 (class 1259 OID 249794)
-- Name: log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 249673)
-- Name: provider; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.provider (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    disabled boolean DEFAULT false NOT NULL,
    disabled_reason text,
    name text,
    domain text,
    file_format character varying(10)
);


ALTER TABLE public.provider OWNER TO admin;

--
-- TOC entry 220 (class 1259 OID 249683)
-- Name: provider_etf; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.provider_etf (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    provider_id integer NOT NULL,
    disabled boolean DEFAULT false NOT NULL,
    disabled_reason text,
    name text,
    isin text,
    ticker text,
    cap_type text,
    style_type text,
    benchmark text,
    trading_since timestamp without time zone,
    number_of_managers integer,
    url text NOT NULL,
    file_format character varying(10)
);


ALTER TABLE public.provider_etf OWNER TO admin;

--
-- TOC entry 222 (class 1259 OID 249699)
-- Name: provider_etf_holding; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.provider_etf_holding (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    provider_etf_id integer NOT NULL,
    trade_date timestamp without time zone NOT NULL,
    ticker text,
    shares double precision,
    market_value double precision,
    weight double precision,
    dividend double precision
);


ALTER TABLE public.provider_etf_holding OWNER TO admin;

--
-- TOC entry 221 (class 1259 OID 249698)
-- Name: provider_etf_holding_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.provider_etf_holding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_etf_holding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 249682)
-- Name: provider_etf_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.provider_etf ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_etf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 249672)
-- Name: provider_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.provider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 249714)
-- Name: ticker; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ticker (
    symbol character varying(32) NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    source character varying(16),
    style_type character varying(16),
    cap_type character varying(16),
    type_from character varying(16),
    isin character varying(16),
    cik character varying(16),
    exchange character varying(32),
    name text,
    industry text,
    sector text,
    invalid text
);


ALTER TABLE public.ticker OWNER TO admin;

--
-- TOC entry 242 (class 1259 OID 249947)
-- Name: ticker_dividend_history; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ticker_dividend_history (
    symbol text NOT NULL,
    ex_date date NOT NULL,
    amount_per_share numeric(18,4) NOT NULL
);


ALTER TABLE public.ticker_dividend_history OWNER TO admin;

--
-- TOC entry 224 (class 1259 OID 249722)
-- Name: ticker_value; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ticker_value (
    symbol character varying(32) NOT NULL,
    value_date date NOT NULL,
    stock_price double precision,
    market_cap double precision
);


ALTER TABLE public.ticker_value OWNER TO admin;

--
-- TOC entry 4859 (class 2606 OID 249875)
-- Name: account_cash_ledger account_cash_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_cash_ledger
    ADD CONSTRAINT account_cash_ledger_pkey PRIMARY KEY (id);


--
-- TOC entry 4867 (class 2606 OID 249967)
-- Name: account_holding_daily account_holding_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_holding_daily
    ADD CONSTRAINT account_holding_daily_pkey PRIMARY KEY (account_id, holding_date, symbol);


--
-- TOC entry 4857 (class 2606 OID 249867)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 4861 (class 2606 OID 249894)
-- Name: account_trade account_trade_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_trade
    ADD CONSTRAINT account_trade_pkey PRIMARY KEY (id);


--
-- TOC entry 4848 (class 2606 OID 249779)
-- Name: best_idea best_idea_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.best_idea
    ADD CONSTRAINT best_idea_pkey PRIMARY KEY (provider_etf_id, symbol, value_date);


--
-- TOC entry 4855 (class 2606 OID 249811)
-- Name: categorize_etf categorize_etf_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.categorize_etf
    ADD CONSTRAINT categorize_etf_pkey PRIMARY KEY (id);


--
-- TOC entry 4846 (class 2606 OID 249764)
-- Name: fund_holding_change fund_holding_change_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fund_holding_change
    ADD CONSTRAINT fund_holding_change_pkey PRIMARY KEY (fund_id, change_date, symbol, direction);


--
-- TOC entry 4844 (class 2606 OID 249747)
-- Name: fund_holding fund_holding_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fund_holding
    ADD CONSTRAINT fund_holding_pkey PRIMARY KEY (fund_id, holding_date, symbol);


--
-- TOC entry 4842 (class 2606 OID 249740)
-- Name: fund fund_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fund
    ADD CONSTRAINT fund_pkey PRIMARY KEY (id);


--
-- TOC entry 4863 (class 2606 OID 249922)
-- Name: interest_rate_config interest_rate_config_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.interest_rate_config
    ADD CONSTRAINT interest_rate_config_pkey PRIMARY KEY (id);


--
-- TOC entry 4853 (class 2606 OID 249802)
-- Name: log log_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_pkey PRIMARY KEY (id);


--
-- TOC entry 4838 (class 2606 OID 249721)
-- Name: ticker pk_ticker; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ticker
    ADD CONSTRAINT pk_ticker PRIMARY KEY (symbol);


--
-- TOC entry 4840 (class 2606 OID 249726)
-- Name: ticker_value pk_ticker_value; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ticker_value
    ADD CONSTRAINT pk_ticker_value PRIMARY KEY (symbol, value_date);


--
-- TOC entry 4836 (class 2606 OID 249706)
-- Name: provider_etf_holding provider_etf_holding_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.provider_etf_holding
    ADD CONSTRAINT provider_etf_holding_pkey PRIMARY KEY (id);


--
-- TOC entry 4832 (class 2606 OID 249691)
-- Name: provider_etf provider_etf_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.provider_etf
    ADD CONSTRAINT provider_etf_pkey PRIMARY KEY (id);


--
-- TOC entry 4829 (class 2606 OID 249681)
-- Name: provider provider_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.provider
    ADD CONSTRAINT provider_pkey PRIMARY KEY (id);


--
-- TOC entry 4865 (class 2606 OID 249953)
-- Name: ticker_dividend_history ticker_dividend_history_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ticker_dividend_history
    ADD CONSTRAINT ticker_dividend_history_pkey PRIMARY KEY (symbol, ex_date);


--
-- TOC entry 4849 (class 1259 OID 249790)
-- Name: fki_fk_best_idea_provider_etf_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX fki_fk_best_idea_provider_etf_id ON public.best_idea USING btree (provider_etf_id) WITH (fillfactor='100', deduplicate_items='true');


--
-- TOC entry 4850 (class 1259 OID 249791)
-- Name: fki_fk_best_idea_symbol; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX fki_fk_best_idea_symbol ON public.best_idea USING btree (symbol) WITH (fillfactor='100', deduplicate_items='true');


--
-- TOC entry 4851 (class 1259 OID 249792)
-- Name: fki_fk_best_idea_value_date; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX fki_fk_best_idea_value_date ON public.best_idea USING btree (value_date) WITH (fillfactor='100', deduplicate_items='true');


--
-- TOC entry 4833 (class 1259 OID 249712)
-- Name: fki_fk_provider_etf_holding_provider_etf_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX fki_fk_provider_etf_holding_provider_etf_id ON public.provider_etf_holding USING btree (provider_etf_id) WITH (fillfactor='100', deduplicate_items='true');


--
-- TOC entry 4830 (class 1259 OID 249697)
-- Name: fki_fk_provider_etf_provider_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX fki_fk_provider_etf_provider_id ON public.provider_etf USING btree (provider_id) WITH (fillfactor='100', deduplicate_items='true');


--
-- TOC entry 4834 (class 1259 OID 249713)
-- Name: idx_provider_etf_holding_trade_date; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_provider_etf_holding_trade_date ON public.provider_etf_holding USING btree (trade_date) WITH (fillfactor='100', deduplicate_items='true');


--
-- TOC entry 4877 (class 2606 OID 249876)
-- Name: account_cash_ledger account_cash_ledger_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_cash_ledger
    ADD CONSTRAINT account_cash_ledger_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- TOC entry 4879 (class 2606 OID 249895)
-- Name: account_trade account_trade_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_trade
    ADD CONSTRAINT account_trade_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- TOC entry 4880 (class 2606 OID 249900)
-- Name: account_trade account_trade_symbol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_trade
    ADD CONSTRAINT account_trade_symbol_fkey FOREIGN KEY (symbol) REFERENCES public.ticker(symbol);


--
-- TOC entry 4878 (class 2606 OID 249881)
-- Name: account_cash_ledger fk_account_cash_ledger_account; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_cash_ledger
    ADD CONSTRAINT fk_account_cash_ledger_account FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- TOC entry 4875 (class 2606 OID 249780)
-- Name: best_idea fk_best_idea_provider_etf_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.best_idea
    ADD CONSTRAINT fk_best_idea_provider_etf_id FOREIGN KEY (provider_etf_id) REFERENCES public.provider_etf(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4876 (class 2606 OID 249785)
-- Name: best_idea fk_best_idea_symbol; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.best_idea
    ADD CONSTRAINT fk_best_idea_symbol FOREIGN KEY (symbol) REFERENCES public.ticker(symbol) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4873 (class 2606 OID 249765)
-- Name: fund_holding_change fk_fund_holding_change_fund_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fund_holding_change
    ADD CONSTRAINT fk_fund_holding_change_fund_id FOREIGN KEY (fund_id) REFERENCES public.fund(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4874 (class 2606 OID 249770)
-- Name: fund_holding_change fk_fund_holding_change_symbol; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fund_holding_change
    ADD CONSTRAINT fk_fund_holding_change_symbol FOREIGN KEY (symbol) REFERENCES public.ticker(symbol) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4871 (class 2606 OID 249748)
-- Name: fund_holding fk_fund_holding_fund_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fund_holding
    ADD CONSTRAINT fk_fund_holding_fund_id FOREIGN KEY (fund_id) REFERENCES public.fund(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4872 (class 2606 OID 249753)
-- Name: fund_holding fk_fund_holding_symbol; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.fund_holding
    ADD CONSTRAINT fk_fund_holding_symbol FOREIGN KEY (symbol) REFERENCES public.ticker(symbol) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4882 (class 2606 OID 249968)
-- Name: account_holding_daily fk_holding_account; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_holding_daily
    ADD CONSTRAINT fk_holding_account FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;


--
-- TOC entry 4883 (class 2606 OID 249973)
-- Name: account_holding_daily fk_holding_symbol; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.account_holding_daily
    ADD CONSTRAINT fk_holding_symbol FOREIGN KEY (symbol) REFERENCES public.ticker(symbol) ON DELETE CASCADE;


--
-- TOC entry 4869 (class 2606 OID 249707)
-- Name: provider_etf_holding fk_provider_etf_holding_provider_etf_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.provider_etf_holding
    ADD CONSTRAINT fk_provider_etf_holding_provider_etf_id FOREIGN KEY (provider_etf_id) REFERENCES public.provider_etf(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4868 (class 2606 OID 249692)
-- Name: provider_etf fk_provider_etf_provider_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.provider_etf
    ADD CONSTRAINT fk_provider_etf_provider_id FOREIGN KEY (provider_id) REFERENCES public.provider(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4870 (class 2606 OID 249727)
-- Name: ticker_value fk_ticker_symbol; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ticker_value
    ADD CONSTRAINT fk_ticker_symbol FOREIGN KEY (symbol) REFERENCES public.ticker(symbol);


--
-- TOC entry 4881 (class 2606 OID 249954)
-- Name: ticker_dividend_history ticker_dividend_history_symbol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ticker_dividend_history
    ADD CONSTRAINT ticker_dividend_history_symbol_fkey FOREIGN KEY (symbol) REFERENCES public.ticker(symbol);


-- Completed on 2026-03-05 19:37:44

--
-- PostgreSQL database dump complete
--

\unrestrict 75OxdbnU1nQZNHMEESMytMt3uTgaAOfknstl9teBtAZUxj0nZrF4gyE8NXxTBEt

