"""
Copy the delta of `provider_etf_holding` rows from the production database into the
development database, so development can be refreshed with real provider data without doing a
full pg_dump/restore of production every time.

For each `provider_etf`, the script finds the latest `holding_date` already present in
development and copies every production holding newer than that (or the full history if
development has none for that ETF yet). Everything else (ticker_value, best_idea,
benchmark_holding, fund_holding, ...) is derived data that gets regenerated by simply running
the normal pipeline against development afterwards, per CLAUDE.md.

`ticker_id` cannot be copied as-is: development's `ticker` table has diverged from
production's (both environments insert new tickers independently via the live pipeline), so
the same ticker can have a different id in each database. Rows are remapped by the
`(symbol, exchange)` natural key instead. Any ticker referenced by the delta that doesn't
exist yet in development is inserted there first (fields only, no `id`/`created_at` — matches
modules/object/ticker.py::upsert_by_symbol's column set). Existing development ticker rows are
never modified.

`provider_etf_id` is assumed to match 1:1 between environments — provider/provider_etf are
admin-managed reference/scraping config, not something either pipeline auto-generates. This is
verified up front; any production provider_etf id missing from development aborts the run
before anything is written (fix `provider`/`provider_etf` manually first).

The script connects directly to both databases at once via psycopg (bypassing
modules/core/db.py's single-environment pool singleton, which can only represent dev *or* prod
per process). The production connection is set to a read-only session as a safety net.

Usage:
    python scripts/_sync_holdings_from_prod.py                        # asks to confirm before committing
    python scripts/_sync_holdings_from_prod.py --yes                  # commit without prompting
    python scripts/_sync_holdings_from_prod.py --dry-run               # run everything, always roll back
    python scripts/_sync_holdings_from_prod.py --provider-etf-id 123   # limit to one ETF, for testing
"""
import argparse
import os
import time

import psycopg
from psycopg import sql
from dotenv import load_dotenv

load_dotenv()

TICKER_COLUMNS = [
    "symbol", "isin", "cusip", "cik", "name", "exchange",
    "industry", "sector", "country", "currency", "source",
    "type_from", "is_actively_trading",
]

# Built with psycopg.sql rather than an f-string so column names are quoted as identifiers
# instead of interpolated as raw text (safe even though TICKER_COLUMNS is a fixed whitelist here).
INSERT_TICKER_SQL = sql.SQL("INSERT INTO ticker ({columns}) VALUES ({placeholders}) RETURNING id;").format(
    columns=sql.SQL(", ").join(map(sql.Identifier, TICKER_COLUMNS)),
    placeholders=sql.SQL(", ").join(sql.Placeholder() for _ in TICKER_COLUMNS),
)

SELECT_TICKERS_BY_ID_SQL = sql.SQL("SELECT id, {columns} FROM ticker WHERE id = ANY(%s);").format(
    columns=sql.SQL(", ").join(map(sql.Identifier, TICKER_COLUMNS)),
)

INSERT_HOLDING_SQL = """
    INSERT INTO provider_etf_holding (provider_etf_id, holding_date, ticker_id, shares, market_value, weight)
    VALUES (%s, %s, %s, %s, %s, %s);
"""


def build_conninfo(prefix: str, db_name_env: str) -> str:
    values = {
        db_name_env: os.getenv(db_name_env),
        f"{prefix}HOST": os.getenv(f"{prefix}HOST"),
        f"{prefix}PORT": os.getenv(f"{prefix}PORT"),
        f"{prefix}USER": os.getenv(f"{prefix}USER"),
        f"{prefix}PASSWORD": os.getenv(f"{prefix}PASSWORD"),
    }
    missing = [k for k, v in values.items() if not v]
    if missing:
        raise SystemExit(f"Missing required environment variable(s): {', '.join(missing)}")
    return (
        f"host={values[f'{prefix}HOST']} port={values[f'{prefix}PORT']} "
        f"dbname={values[db_name_env]} user={values[f'{prefix}USER']} "
        f"password={values[f'{prefix}PASSWORD']}"
    )


def connect_dev() -> psycopg.Connection:
    conn = psycopg.connect(build_conninfo("SECRET_DATABASE_", "SECRET_DATABASE_NAME"))
    print(f"[dev]  connected to {conn.info.dbname}@{conn.info.host}")
    return conn


def connect_prod() -> psycopg.Connection:
    conn = psycopg.connect(build_conninfo("SECRET_DATABASE_PROD_", "SECRET_DATABASE_PROD_NAME"))
    # Belt and braces: this script must never write to production, no matter what the code above does.
    conn.execute("SET default_transaction_read_only = on;")
    conn.commit()
    print(f"[prod] connected to {conn.info.dbname}@{conn.info.host} (read-only session)")
    return conn


def fetch_dev_max_dates(dev_conn: psycopg.Connection) -> dict:
    with dev_conn.cursor() as cur:
        cur.execute("SELECT provider_etf_id, MAX(holding_date) FROM provider_etf_holding GROUP BY provider_etf_id;")
        return dict(cur.fetchall())


def fetch_dev_ticker_map(dev_conn: psycopg.Connection) -> dict:
    with dev_conn.cursor() as cur:
        cur.execute("SELECT symbol, exchange, id FROM ticker;")
        return {(symbol, exchange): ticker_id for symbol, exchange, ticker_id in cur.fetchall()}


def fetch_provider_etf_names(conn: psycopg.Connection) -> dict:
    with conn.cursor() as cur:
        cur.execute("SELECT id, COALESCE(name, ticker, isin, id::text) FROM provider_etf ORDER BY id;")
        return dict(cur.fetchall())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true", help="Run the whole sync but always roll back at the end.")
    parser.add_argument("--yes", action="store_true", help="Commit without an interactive confirmation prompt.")
    parser.add_argument("--provider-etf-id", type=int, default=None, help="Limit the sync to a single provider_etf id (for testing).")
    args = parser.parse_args()

    started = time.monotonic()
    dev_conn = connect_dev()
    prod_conn = connect_prod()

    try:
        dev_etf_names = fetch_provider_etf_names(dev_conn)
        prod_etf_names = fetch_provider_etf_names(prod_conn)

        target_ids = [args.provider_etf_id] if args.provider_etf_id else sorted(prod_etf_names)
        missing_in_dev = [i for i in target_ids if i not in dev_etf_names]
        if missing_in_dev:
            raise SystemExit(
                "Aborting: these provider_etf ids exist in production but not in development: "
                f"{missing_in_dev}. provider_etf config isn't auto-generated by the pipeline — "
                "sync it manually before holdings can be copied."
            )

        dev_max_dates = fetch_dev_max_dates(dev_conn)
        dev_ticker_map = fetch_dev_ticker_map(dev_conn)

        # --- Phase 1: pull the delta rows from production, per ETF ---
        delta_by_etf = {}
        referenced_ticker_ids = set()
        for etf_id in target_ids:
            cutoff = dev_max_dates.get(etf_id)
            with prod_conn.cursor() as cur:
                if cutoff is None:
                    cur.execute(
                        "SELECT holding_date, ticker_id, shares, market_value, weight "
                        "FROM provider_etf_holding WHERE provider_etf_id = %s ORDER BY holding_date;",
                        (etf_id,),
                    )
                else:
                    cur.execute(
                        "SELECT holding_date, ticker_id, shares, market_value, weight "
                        "FROM provider_etf_holding WHERE provider_etf_id = %s AND holding_date > %s ORDER BY holding_date;",
                        (etf_id, cutoff),
                    )
                rows = cur.fetchall()
            if rows:
                delta_by_etf[etf_id] = rows
                referenced_ticker_ids.update(r[1] for r in rows if r[1] is not None)

        if not delta_by_etf:
            print("Development is already up to date with production. Nothing to do.")
            return

        # --- Phase 2: resolve every referenced ticker_id to its development equivalent,
        #     creating any missing tickers in development along the way ---
        ticker_id_map = {}
        new_ticker_count = 0
        if referenced_ticker_ids:
            with prod_conn.cursor() as cur:
                cur.execute(SELECT_TICKERS_BY_ID_SQL, (list(referenced_ticker_ids),))
                prod_tickers = cur.fetchall()

            missing_prod_tickers = referenced_ticker_ids - {row[0] for row in prod_tickers}
            if missing_prod_tickers:
                print(f"  warning: {len(missing_prod_tickers)} ticker_id(s) referenced by holdings no longer exist in production, "
                      "those holding rows will be skipped: " + ", ".join(str(i) for i in sorted(missing_prod_tickers)))

            with dev_conn.cursor() as cur:
                for prod_ticker_id, *field_values in prod_tickers:
                    symbol, exchange = field_values[0], field_values[5]
                    key = (symbol, exchange)
                    dev_ticker_id = dev_ticker_map.get(key)
                    if dev_ticker_id is None:
                        cur.execute(INSERT_TICKER_SQL, field_values)
                        row = cur.fetchone()
                        if row is None:
                            raise RuntimeError(f"INSERT INTO ticker for symbol={symbol!r} exchange={exchange!r} did not return an id")
                        dev_ticker_id = row[0]
                        dev_ticker_map[key] = dev_ticker_id
                        new_ticker_count += 1
                    ticker_id_map[prod_ticker_id] = dev_ticker_id

        # --- Phase 3: insert the mapped holding rows into development ---
        total_rows = 0
        skipped_rows = 0
        summary_lines = []
        for etf_id, rows in delta_by_etf.items():
            insert_rows = []
            for holding_date, ticker_id, shares, market_value, weight in rows:
                dev_ticker_id = None
                if ticker_id is not None:
                    dev_ticker_id = ticker_id_map.get(ticker_id)
                    if dev_ticker_id is None:
                        skipped_rows += 1
                        continue
                insert_rows.append((etf_id, holding_date, dev_ticker_id, shares, market_value, weight))

            if insert_rows:
                with dev_conn.cursor() as cur:
                    cur.executemany(INSERT_HOLDING_SQL, insert_rows)
                total_rows += len(insert_rows)
                cutoff = dev_max_dates.get(etf_id)
                note = " (full history — no prior dev data)" if cutoff is None else ""
                summary_lines.append(
                    f"  provider_etf {etf_id:>4} ({dev_etf_names.get(etf_id, '?')}): "
                    f"+{len(insert_rows)} rows, {rows[0][0].date()} .. {rows[-1][0].date()}{note}"
                )

        print()
        print("\n".join(summary_lines))
        print()
        print(f"Total: {total_rows} holding rows across {len(delta_by_etf)} provider_etf(s), "
              f"{new_ticker_count} new ticker(s) created, {skipped_rows} row(s) skipped (dangling ticker_id).")
        print(f"Elapsed: {time.monotonic() - started:.1f}s")

        if args.dry_run:
            dev_conn.rollback()
            print("\n--dry-run: rolled back, nothing was committed.")
            return

        if args.yes or input("\nCommit these changes to the development database? [y/N] ").strip().lower() == "y":
            dev_conn.commit()
            print("Committed.")
        else:
            dev_conn.rollback()
            print("Aborted, changes rolled back.")

    except BaseException:
        dev_conn.rollback()
        raise
    finally:
        prod_conn.rollback()
        dev_conn.close()
        prod_conn.close()


if __name__ == "__main__":
    main()
